#!/usr/bin/env python3
"""Generate a local `.env` with dev validator keys + cluster token for compose.

The repository ships NO secrets. Run this once before `docker compose up` to
materialize a gitignored `.env` the compose file interpolates:

    python scripts/gen_dev_secrets.py

For production, generate keys with `python -m helix_blockchain.tools.keygen` and
provide them via your secret manager (Vault/KMS) or a mounted file
(HELIX_NODE__PRIVATE_KEY_FILE), never committed.
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from helix_blockchain.domain.crypto import PrivateKey  # noqa: E402

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"


def main() -> int:
    if ENV_PATH.exists():
        print(f"refusing to overwrite existing {ENV_PATH}")
        return 1
    lines = ["# DEV-ONLY secrets generated by scripts/gen_dev_secrets.py — DO NOT COMMIT"]
    keys = [PrivateKey.generate() for _ in range(3)]
    for i, key in enumerate(keys, start=1):
        lines.append(f"NODE{i}_KEY={key.to_hex()}")
        lines.append(f"NODE{i}_PUB={key.public.to_hex()}")
    lines.append(f"CLUSTER_TOKEN={secrets.token_urlsafe(32)}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {ENV_PATH} with 3 dev keypairs + a random cluster token")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
